from trading.strategies.simulation.TraidingStrategy import TraidingStrategy
from trading.strategies.simulation.Sma2Porcentaje import Sma2Porcentaje
from trading.strategies.simulation.Sma4Porcentaje import Sma4Porcentaje